version: "3.9"

# Quick-start Compose for Clip Relay
# 1) Copy this file to your server (e.g., /srv/clip-relay/compose.yml)
# 2) Create .env alongside with DATABASE_URL and CLIPBOARD_PASSWORD
# 3) Choose the image tag: prefer sha-<commit> for reproducible deploys

services:
  app:
    # Rust API + static frontend image
    # Replace with your registry and namespace
    # Examples:
    #   ghcr.io/OWNER/REPO/clip-relay:sha-<GITHUB_SHA>
    #   ghcr.io/OWNER/REPO/clip-relay:latest
    image: REGISTRY/NAMESPACE/clip-relay:latest
    ports:
      - "8087:8087"   # container listens on 8087 by default
    env_file: .env      # should contain CLIPBOARD_PASSWORD
    # Optionally override port:
    # environment:
    #   - PORT=8087
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    pull_policy: always

# .env example:
# DATABASE_URL="file:../data/custom.db"
# CLIPBOARD_PASSWORD="change-me"
