export const copy = {
  shell: {
    noBundleImported: '还没有导入接入包。',
    noUploadsYet: '还没有上传记录。',
    noNativeShareYet: '暂时还没有收到系统分享内容。',
  },
  embedded: {
    defaultEmpty: '先导入接入包，再在应用内启动 Clip Relay。',
    fallbackBadge: '\u5185\u5d4c\u53d7\u9650',
    badge: {
      launching: '正在启动',
      live: '运行中',
      loadError: '加载失败',
      standby: '待命中',
      ready: '已就绪',
    },
    booting: '正在启动内嵌版 Clip Relay 并注入设备凭证...',
    standby: '内嵌视图已暂停，随时都可以从原生壳重新打开。',
    imported: '接入包已导入，可以直接启动内嵌版应用。',
    ready: '已准备好打开内嵌版 Clip Relay。',
    loadedAt: (time: string) => `已加载，时间 ${time}`,
    loadError: '内嵌页面加载失败了。你可以重新加载，或者先退回原生壳。',
    targetNeedsHttps: (url: string) => `内嵌模式当前要求使用 HTTPS 地址，当前目标是 ${url}。`,
    loadTimeout: '内嵌页面长时间没有完成加载，通常是 HTTPS、证书或 frame 限制导致的。',
    fallbackTitle: '当前无法在应用内嵌打开',
    fallbackHint: '你仍然可以先用系统浏览器打开服务端，或者复制地址后到别处排查。',
  },
  fields: {
    serverUrl: '服务器地址',
    apiBase: 'API 基址',
    deviceToken: '设备凭证',
    generatedAt: '生成时间',
    target: '目标地址',
    status: '状态',
    action: '动作',
    mimeType: 'MIME 类型',
    subject: '主题',
    text: '文本',
    uriCount: 'URI 数量',
  },
  badges: {
    configured: '已配置',
    shareReceived: '已收到分享',
  },
  buttons: {
    importSharedFiles: '导入共享文件',
    importSharedFilesShort: '导入分享',
    openInBrowser: '浏览器打开',
    copyAddress: '复制地址',
    backToShell: '\u8fd4\u56de\u539f\u751f\u58f3',
  },
  status: {
    openingEmbedded: (url: string) => `正在打开 ${url} 的内嵌 Clip Relay...`,
    embeddedBlocked: (message: string) => `内嵌模式不可用：${message}`,
    returnedToShell: '已返回原生壳。',
    importFailed: '导入失败：JSON 不是有效的 Clip Relay 移动端接入包。',
    importedBundle: (apiBase: string) => `已导入接入包：${apiBase}`,
    openingPhotoPicker: '正在打开系统相册...',
    noPhotosSelected: '没有选中任何照片。',
    galleryUploading: (count: number) => `正在上传 ${count} 个相册项目...`,
    galleryFinished: '相册上传完成。',
    photoPickerCancelled: '已取消相册选择。',
    photoPickerFailed: (message: string) => `相册选择失败：${message}`,
    openingCamera: '正在打开相机...',
    cameraUploading: '正在上传刚拍摄的照片...',
    cameraFinished: '拍照上传完成。',
    cameraCancelled: '已取消拍照。',
    cameraFailed: (message: string) => `拍照失败：${message}`,
    nativeShareDetected: (count: number) => `检测到系统分享内容（${count} 个 URI）。`,
    nativeShareReceived: (count: number) => `已收到系统分享内容（${count} 个 URI）。`,
    checkingConnection: (apiBase: string) => `正在检查 ${apiBase} ...`,
    connectionOk: (detail: string) => `连接正常：${detail}`,
    connectionFailed: (detail: string) => `连接失败：${detail}`,
    bundleCleared: '已清除本地保存的接入包。',
    textSent: '文本已发送到 Clip Relay。',
    textSendFailed: (message: string) => `文本发送失败：${message}`,
    resolvingSharedFiles: (count: number) => `正在解析 Android 分享过来的 ${count} 个文件...`,
    noSharedFilesReturned: 'Android 没有返回可上传的共享文件。',
    sharedUploading: (count: number) => `正在上传 ${count} 个共享文件...`,
    sharedFinished: '共享文件上传完成。',
    sharedImportFailed: (message: string) => `共享文件导入失败：${message}`,
    uploadBatchStart: (count: number) => `正在上传 ${count} 个文件...`,
    uploadBatchFinished: '文件批量上传完成。',
    uploadBatchFinishedWithFailures: (finishedMessage: string, failedCount: number) => `${finishedMessage} 其中 ${failedCount} 个失败。`,
    loadedSavedBundle: (apiBase: string) => `已载入保存的接入包：${apiBase}`,
    readyForImport: '准备就绪。请先导入网页设置面板导出的接入包。',
    copiedAddress: '已复制服务端地址。',
    copyAddressFailed: '复制地址失败，请稍后重试。',
  },
  uploadDetail: {
    waiting: '等待中',
    uploading: '上传中',
    uploaded: '已上传',
  },
  errors: {
    noReadableCameraUrl: '相机插件没有返回可读取的文件地址。',
    unableToReadCapturedMedia: (status: number) => `读取拍摄结果失败（${status}）。`,
    invalidServerUrl: '接入包中的服务器地址不是有效 URL。',
  },
};