name: Build and Push Docker Image

# Manual trigger only to avoid building on every push
on:
  workflow_dispatch:
    inputs:
      build_slim:
        description: "Also build and push the slim image"
        type: boolean
        required: false
        default: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a Linux environment to build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          # You need to set these as secrets in your GitHub repository settings
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image (latest + sha)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/cloud-clipboard:latest
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/cloud-clipboard:sha-${{ github.sha }}

      - name: Build and push Docker image (slim + sha)
        if: inputs.build_slim == true
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.slim
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/cloud-clipboard:slim
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/cloud-clipboard:slim-${{ github.sha }}
