name: Build and Push Docker Image

# Manual trigger only to avoid building on every push
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a Linux environment to build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (enable cross-arch emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          # You need to set these as secrets in your GitHub repository settings
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/clip-relay:${{ steps.extract_branch.outputs.branch }}
            ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_NAMESPACE }}/clip-relay:${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && format('{0}/{1}/clip-relay:latest', secrets.REGISTRY_URL, secrets.REGISTRY_NAMESPACE) || '' }}
